# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ccaa038a8af43e4893dba9a2309f1b3a4fc3a0f2f1595afaedd8ea551bbbd69a262fe4963daf591dba3415c553ffa9f6cb27cca2c4e8caa9f3b3cbd2eee711f2

test:
  secret_key_base: 550c605199b6706e4e0b44a73b521cbba7c35e02915cf5e3e54a10b2852c76d1c3bf49c35c9806b96f34389542eade7ce5048834db2d43b80d487bb3ffc9c063

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
